import { NextRequest, NextResponse } from "next/server";
import { exec } from "child_process";
import { promisify } from "util";
import { getCurrentUser } from "@/lib/firebase/session";
import { z } from "zod";
import { db } from "@/lib/initializations/db";
import { JOB_STATUS, LanguageCode, SUPPORTED_LANGUAGES } from "@/helpers/const";
import { randomUUID } from "crypto";
import {
  normalizeAutoGenerated,
  parseVtt,
  parseVttForAutoGeneratedYT,
} from "@/lib/scripts/subtitle-parser";

const execAsync = promisify(exec);
const YTDLP_PATH = "/opt/homebrew/bin/yt-dlp";

export interface SubtitleInfo {
  available: Record<string, TrackEntry>;
  autoGenerated: Record<string, TrackEntry>;
  allLanguages: string[];
}

interface TrackEntry {
  ext: string;
  url: string;
}

interface VideoInfo {
  subtitles?: Record<string, TrackEntry[]>;
  automatic_captions?: Record<string, TrackEntry[]>;
}

async function getVideoInfo(videoId: string): Promise<VideoInfo> {
  const url = `https://www.youtube.com/watch?v=${videoId}`;

  const { stdout } = await execAsync(`${YTDLP_PATH} -J "${url}"`, {
    timeout: 30_000,
  });

  return JSON.parse(stdout);
}

function filterTracks(
  tracks?: Record<string, TrackEntry[]>,
): Record<string, TrackEntry> {
  if (!tracks) return {};

  return Object.fromEntries(
    Object.entries(tracks)
      .filter(([lang]) => SUPPORTED_LANGUAGES.has(lang as LanguageCode))
      .flatMap(([lang, entries]) => {
        const vtt = entries.find((entry) => entry.ext === "vtt");
        return vtt ? [[lang, vtt]] : [];
      }),
  );
}

export async function GET(req: NextRequest) {
  const user = await getCurrentUser();
  if (!user)
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const videoId = req.nextUrl.searchParams.get("videoId");
  if (!videoId) {
    return NextResponse.json({ error: "Missing videoId" }, { status: 400 });
  }

  try {
    const info = await getVideoInfo(videoId);

    const available = filterTracks(info.subtitles);
    const autoGenerated = filterTracks(info.automatic_captions);

    const allLanguages = [
      ...new Set([...Object.keys(available), ...Object.keys(autoGenerated)]),
    ];

    return NextResponse.json({
      available,
      autoGenerated,
      allLanguages,
    } satisfies SubtitleInfo);
  } catch (err) {
    console.error("yt-dlp list-subs error:", err);
    return NextResponse.json(
      { error: "Failed to fetch subtitle list" },
      { status: 500 },
    );
  }
}

interface SubtitleTrack {
  url: string;
  isSource: boolean;
  language: string;
  isAutoGenerated: boolean;
}

const SubtitleTrackSchema = z.object({
  url: z.string().url(),
  language: z.string().min(2),
  isSource: z.boolean(),
  isAutoGenerated: z.boolean(),
});

const BodySchema = z.object({
  mediaId: z.string().uuid(),
  sourceLang: z.string().min(2),
  subtitleTracks: z.array(SubtitleTrackSchema),
  translateMethod: z.enum(["youtube", "libretranslate", "deepL"]),
});

async function fetchSubtitleLines(track: SubtitleTrack, retries = 3) {
  const url = new URL(track.url);

  if (url.protocol !== "https:" || !url.hostname.endsWith("youtube.com")) {
    throw new Error("Invalid subtitle URL");
  }

  const res = await fetch(track.url);

  if (res.status === 429 && retries > 0) {
    console.warn(`429 for ${track.language}, retrying in 5s...`);
    await sleep(5_000);
    return fetchSubtitleLines(track, retries - 1);
  }

  if (!res.ok)
    throw new Error(`Failed to fetch subtitles for ${track.language}`);

  if (track.isAutoGenerated)
    return normalizeAutoGenerated(parseVttForAutoGeneratedYT(await res.text()));

  return parseVtt(await res.text());
}

export async function POST(req: NextRequest) {
  const user = await getCurrentUser();
  if (!user)
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const parsed = BodySchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json(
      { error: "Invalid request", details: parsed.error.flatten() },
      { status: 400 },
    );
  }

  const { mediaId, sourceLang, subtitleTracks, translateMethod } = parsed.data;

  if (translateMethod !== "youtube") {
    return NextResponse.json(
      {
        error: `Route not available for this translation method (${translateMethod})`,
      },
      { status: 400 },
    );
  }

  const media = await db.mediaContent.findUnique({
    where: { id: mediaId },
    select: { user_id: true, job_status: true },
  });

  if (!media || media.user_id !== user.id) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  if (
    media.job_status === JOB_STATUS.RUNNING ||
    media.job_status === JOB_STATUS.PENDING
  ) {
    return NextResponse.json({ error: "Job already running" }, { status: 409 });
  }

  await db.mediaContent.update({
    where: { id: mediaId },
    data: { job_status: JOB_STATUS.PENDING, job_progress: 0 },
  });

  processYouTubeSubtitles({
    mediaContentId: mediaId,
    subtitleTracks,
    sourceLang,
  }).catch(async (err) => {
    console.error("YouTube subtitles processing error:", err);
    await db.mediaContent.update({
      where: { id: mediaId },
      data: { job_status: JOB_STATUS.ERROR, job_progress: 0 },
    });
  });

  return NextResponse.json({ ok: true, mediaId });
}

async function processYouTubeSubtitles({
  mediaContentId,
  subtitleTracks,
  sourceLang,
}: {
  mediaContentId: string;
  subtitleTracks: SubtitleTrack[];
  sourceLang: string;
}) {
  await db.mediaContent.update({
    where: { id: mediaContentId },
    data: { job_status: JOB_STATUS.RUNNING, job_progress: 5 },
  });

  const sourceTrack = subtitleTracks.find((e) => e.isSource);
  if (!sourceTrack) {
    throw new Error(`No source subtitles available for ${sourceLang}`);
  }

  const sourceLines = await fetchSubtitleLines(sourceTrack);

  if (!sourceLines) {
    throw new Error(`No subtitles available for ${sourceLang}`);
  }

  await db.mediaContent.update({
    where: { id: mediaContentId },
    data: { job_progress: 50 },
  });

  await upsertTrack(sourceLines, {
    mediaContentId,
    language: sourceLang,
    isSource: true,
  });

  // wait after fetchSubtitleLines to avoid hitting 429
  await sleep(5_000);

  await db.mediaContent.update({
    where: { id: mediaContentId },
    data: {
      source_language: sourceLang,
      job_progress: 75,
    },
  });

  const translationTracks = subtitleTracks.filter((e) => !e.isSource);

  for (const [index, track] of translationTracks.entries()) {
    const transLines = await fetchSubtitleLines(track);

    if (!transLines) {
      console.warn(`No YouTube subtitles for ${track.language}, skipping`);
      continue;
    }

    await upsertTrack(transLines, {
      mediaContentId,
      language: track.language,
      isSource: false,
    });

    if (index < translationTracks.length - 1) {
      await sleep(5_000);
    }
  }

  await db.mediaContent.update({
    where: { id: mediaContentId },
    data: { job_status: JOB_STATUS.DONE, job_progress: 100 },
  });
}

async function upsertTrack(
  lines: { index: number; start_ms: number; end_ms: number; text: string }[],
  trackData: { mediaContentId: string; language: string; isSource: boolean },
) {
  const existing = await db.subtitleTrack.findUnique({
    where: {
      media_content_id_language: {
        media_content_id: trackData.mediaContentId,
        language: trackData.language,
      },
    },
    select: { id: true },
  });

  if (existing) {
    await db.subtitleLine.deleteMany({
      where: { subtitle_track_id: existing.id },
    });
    await db.subtitleTrack.delete({ where: { id: existing.id } });
  }

  const track = await db.subtitleTrack.create({
    data: {
      media_content_id: trackData.mediaContentId,
      language: trackData.language,
      is_source: trackData.isSource,
    },
  });

  await db.subtitleLine.createMany({
    data: lines.map((l) => ({
      id: randomUUID(),
      media_content_id: trackData.mediaContentId,
      subtitle_track_id: track.id,
      index: l.index,
      start_ms: l.start_ms,
      end_ms: l.end_ms,
      text: l.text,
    })),
  });
}

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
