import { SubtitleInfo } from "@/app/api/youtube/subtitles/route";
import { useState, useTransition } from "react";

interface Args {
  sourceLanguage: string;
  translationLanguages: string[];
  acquisitionMethod: string;
  translateMethod: string;
  videoId: string;
  ytSubtitlesInfo?: SubtitleInfo;

  translationsFileUpload: { extractPathsMap: () => Record<string, string> };
  onSuccess: (mediaId: string) => void;
}

export function useHandleContentSubmit(args: Args) {
  const {
    sourceLanguage,
    translationLanguages,
    acquisitionMethod,
    translateMethod,
    videoId,
    ytSubtitlesInfo,
    translationsFileUpload,
    onSuccess,
  } = args;

  const [error, setError] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();

  const shouldRunIngest =
    acquisitionMethod !== "youtube" ||
    (translateMethod !== "youtube" && translationLanguages.length > 0);

  async function createMedia() {
    const infoRes = await fetch("/api/youtube/info", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        url: `https://www.youtube.com/watch?v=${videoId}`,
        sourceLang: sourceLanguage,
      }),
    });

    if (!infoRes.ok) {
      const data = await infoRes.json();
      setError(data.error ?? "Failed to add video");
      return;
    }

    const { id: mediaId } = await infoRes.json();

    return mediaId;
  }

  async function handleSubmitWithYT(mediaId: string) {
    if (!ytSubtitlesInfo) return;

    const subtitleTracks = Object.entries({
      ...ytSubtitlesInfo.available,
      ...ytSubtitlesInfo.autoGenerated,
    }).map(([lang, track]) => ({
      url: track.url,
      language: lang,
      isSource: lang === sourceLanguage,
    }));

    await fetch("/api/youtube/subtitles", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        mediaId,
        sourceLang: sourceLanguage,
        subtitleTracks,
        translateMethod,
      }),
    });
  }

  async function handleSubmitWithUpload(mediaId: string) {
    const translateFiles = translationsFileUpload.extractPathsMap();

    const ingestRes = await fetch(`/api/subtitles/${mediaId}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        sourceLang: sourceLanguage,
        acquisitionMethod,
        youtubeVideoId: videoId,
        translateLangs: translationLanguages,
        translateMethod,
        removeLangs: [],
        ...(translateFiles && Object.keys(translateFiles).length > 0
          ? { translateFiles }
          : {}),
      }),
    });

    if (!ingestRes.ok) {
      const data = await ingestRes.json();
      setError(data.error ?? "Failed to start subtitle ingestion");
      return;
    }
  }

  function handleSubmit() {
    setError(null);

    startTransition(async () => {
      const mediaId = await createMedia();

      if (shouldRunIngest) handleSubmitWithUpload(mediaId);
      else handleSubmitWithYT(mediaId);

      onSuccess(mediaId);
    });
  }

  return {
    error,
    isPending,
    handleSubmit,
  };
}
