import { beforeEach, describe, expect, it, vi } from "vitest";
import { renderHook, waitFor } from "@testing-library/react";

import { useYouTubeSubtitles } from "@/hooks/useYouTubeSubtitles";
import { createWrapper } from "@/helpers/tests/providers";

beforeEach(() => {
  vi.resetAllMocks();
});

describe("useYouTubeSubtitles", () => {
  it("does not fetch when videoId is null", () => {
    const fetchMock = vi.fn();
    global.fetch = fetchMock;

    const { result } = renderHook(() => useYouTubeSubtitles(null), {
      wrapper: createWrapper(),
    });

    expect(result.current.fetchStatus).toBe("idle");
    expect(fetchMock).not.toHaveBeenCalled();
  });

  it("fetches YouTube subtitles successfully", async () => {
    const response = {
      available: {
        en: { url: "https://example.com/en.vtt" },
      },
      autoGenerated: {},
    };

    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: () => Promise.resolve(response),
    });

    const { result } = renderHook(() => useYouTubeSubtitles("video-123"), {
      wrapper: createWrapper(),
    });

    await waitFor(() => {
      expect(result.current.data).toEqual(response);
    });

    expect(fetch).toHaveBeenCalledWith(
      "/api/youtube/subtitles?videoId=video-123",
    );
  });

  it("handles fetch errors", async () => {
    global.fetch = vi.fn().mockResolvedValue({
      ok: false,
    });

    const { result } = renderHook(() => useYouTubeSubtitles("video-123"), {
      wrapper: createWrapper(),
    });

    await waitFor(() => {
      expect(result.current.isError).toBe(true);
    });

    expect(result.current.error?.message).toBe(
      "Failed to fetch YouTube subtitles",
    );
  });

  it("encodes the video ID in the request", async () => {
    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: () => Promise.resolve({}),
    });

    renderHook(() => useYouTubeSubtitles("video id?"), {
      wrapper: createWrapper(),
    });

    await waitFor(() => {
      expect(fetch).toHaveBeenCalledWith(
        "/api/youtube/subtitles?videoId=video id?",
      );
    });
  });
});
